version: 2.1
defaults: &defaults
  docker:
    - image: docker:20.10.7
jobs:
  Build-And-Push:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Docker
          command: |
            apk add --no-cache docker
      - setup_remote_docker
      - run:
          name: tag
          command: |
            IMAGE_TAG=$CIRCLE_TAG
            echo $IMAGE_TAG
      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKER_USERNAME/$DOCKER_REGISTRY:$CIRCLE_TAG .
      - run:
          name: Push Docker image
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker tag $DOCKER_USERNAME/$DOCKER_REGISTRY:$CIRCLE_TAG $DOCKER_USERNAME/$DOCKER_REGISTRY:latest
            docker push $DOCKER_USERNAME/$DOCKER_REGISTRY:$CIRCLE_TAG
            docker push $DOCKER_USERNAME/$DOCKER_REGISTRY:latest

  Deploy:
    machine: true
    resource_class: compliancefoundry/cf
    steps:
      - run: 
          name: Stop Container
          command: |
            docker-compose -f /home/ec2-user/final-cf/docker-compose.yml stop $SERVICE_NAME
      - run:
          name: Pull Docker image
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker-compose -f /home/ec2-user/final-cf/docker-compose.yml pull $SERVICE_NAME
      - run:
          name: Up Migration
          command: |
            docker-compose -f /home/ec2-user/final-cf/docker-compose.yml up -d $SERVICE_NAME_MIGRATION 
      - run:
          name: Up service
          command: |
            docker-compose -f /home/ec2-user/final-cf/docker-compose.yml up -d $SERVICE_NAME                     
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - Build-And-Push:
          filters:
            tags:
              only: [/^v\d+\.\d+\.\d+$/]
            branches:
              ignore: /.*/
      - Deploy:
          requires:
            - Build-And-Push
          filters:
            tags:
              only: [/^v\d+\.\d+\.\d+$/]
            branches:
                ignore: /.*/


