"""license key

Revision ID: 001b0761c604
Revises: 589b4b7d4ef1
Create Date: 2024-03-06 11:46:14.980891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001b0761c604'
down_revision: Union[str, None] = '589b4b7d4ef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('license_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_license_key', sa.String(), nullable=False),
    sa.Column('user_subscription_id', sa.Integer(), nullable=True),
    sa.Column('in_use', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_subscription_id'], ['user_subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('license_keys')
    # ### end Alembic commands ###
